<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-5HL70CFF" ignored="1" name="loginTest" tests="3" failures="2" timestamp="2022-09-23T22:38:13 EDT" time="13.42" errors="0">
  <testcase name="TC002_user_login_with_valid_and_invalid_credential" time="3.754" classname="com.demobanking.testcase.Login_Test"/>
  <testcase name="TC002_user_login_with_valid_and_invalid_credential" time="1.618" classname="com.demobanking.testcase.Login_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.demobanking.testcase.Login_Test.TC002_user_login_with_valid_and_invalid_credential(Login_Test.java:56)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC002_user_login_with_valid_and_invalid_credential -->
  <testcase name="TC002_user_login_with_valid_and_invalid_credential" time="1.916" classname="com.demobanking.testcase.Login_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.demobanking.testcase.Login_Test.TC002_user_login_with_valid_and_invalid_credential(Login_Test.java:56)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC002_user_login_with_valid_and_invalid_credential -->
  <testcase name="TC001_user_login_with_valid_credential" time="0.0" classname="com.demobanking.testcase.Login_Test">
    <ignored/>
  </testcase> <!-- TC001_user_login_with_valid_credential -->
</testsuite> <!-- loginTest -->
