<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-5HL70CFF" ignored="0" name="Test1" tests="4" failures="4" timestamp="2022-09-13T13:34:59 EDT" time="17.925" errors="0">
  <testcase name="TC001_user_login_with_valid_credential" time="2.304" classname="com.demobanking.testcase.Login_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.demobanking.testcase.Login_Test.TC001_user_login_with_valid_credential(Login_Test.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC001_user_login_with_valid_credential -->
  <testcase name="TC002_user_login_with_valid_and_invalid_credential" time="2.006" classname="com.demobanking.testcase.Login_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.demobanking.testcase.Login_Test.TC002_user_login_with_valid_and_invalid_credential(Login_Test.java:69)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC002_user_login_with_valid_and_invalid_credential -->
  <testcase name="TC002_user_login_with_valid_and_invalid_credential" time="2.139" classname="com.demobanking.testcase.Login_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.demobanking.testcase.Login_Test.TC002_user_login_with_valid_and_invalid_credential(Login_Test.java:55)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC002_user_login_with_valid_and_invalid_credential -->
  <testcase name="TC002_user_login_with_valid_and_invalid_credential" time="2.019" classname="com.demobanking.testcase.Login_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.demobanking.testcase.Login_Test.TC002_user_login_with_valid_and_invalid_credential(Login_Test.java:55)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC002_user_login_with_valid_and_invalid_credential -->
</testsuite> <!-- Test1 -->
